name: 'Install SDL Packages'
description: 'Install SDL packages'
author: 'Scott Doxey @neogeek'
branding:
  color: blue
  icon: upload-cloud

inputs:
  CACHE_SDL:
    description: 'If the action should cache the SDL files.'
    required: false
    default: 'true'
  CACHE_SDL_IMAGE:
    description: 'If the action should cache the SDL_image files.'
    required: false
    default: 'true'
  CACHE_SDL_TTF:
    description: 'If the action should cache the SDL_ttf files.'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Restore SDL2 Cache
      uses: actions/cache/restore@v4.0.2
      id: cache-sdl
      with:
        path: /tmp/.sdl/SDL2-2.30.5
        key: sdl2-${{ runner.os }}-sdl

    - if: steps.cache-sdl.outputs.cache-hit != 'true'
      name: Install SDL2-2.30.5
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL/releases/download/release-2.30.5/SDL2-2.30.5.tar.gz
        tar -xzvf SDL2-2.30.5.tar.gz
        cd SDL2-2.30.5
        ./configure --prefix=/tmp/.sdl/SDL2-2.30.5
        make
        sudo make install

    - if: ${{ inputs.CACHE_SDL != 'false' }} && steps.cache-sdl.outputs.cache-hit != 'true'
      name: Store SDL2 Cache
      uses: actions/cache/save@v4.0.2
      with:
        path: /tmp/.sdl/SDL2-2.30.5
        key: sdl2-${{ runner.os }}-sdl

    - name: Restore SDL2_image Cache
      uses: actions/cache/restore@v4.0.2
      id: cache-sdl-image
      with:
        path: /tmp/.sdl/SDL2_image-2.8.2
        key: sdl2-${{ runner.os }}-sdl-image

    - if: steps.cache-sdl-image.outputs.cache-hit != 'true'
      name: Install SDL_image
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL_image/releases/download/release-2.8.2/SDL2_image-2.8.2.tar.gz
        tar -xzvf SDL2_image-2.8.2.tar.gz
        cd SDL2_image-2.8.2
        ./configure --prefix=/tmp/.sdl/SDL2_image-2.8.2
        make
        sudo make install
      env:
        PKG_CONFIG_PATH: /tmp/.sdl/SDL2-2.30.5/lib/pkgconfig:$PKG_CONFIG_PATH

    - if: ${{ inputs.CACHE_SDL_IMAGE != 'false' }} && steps.cache-sdl-image.outputs.cache-hit != 'true'
      name: Store SDL2_image Cache
      uses: actions/cache/save@v4.0.2
      with:
        path: /tmp/.sdl/SDL2_image-2.8.2
        key: sdl2-${{ runner.os }}-sdl-image

    - name: Restore SDL2_ttf Cache
      uses: actions/cache/restore@v4.0.2
      id: cache-sdl-ttf
      with:
        path: /tmp/.sdl/SDL2_ttf-2.22.0
        key: sdl2-${{ runner.os }}-sdl-ttf

    - if: steps.cache-sdl-ttf.outputs.cache-hit != 'true'
      name: Install SDL_ttf
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.22.0/SDL2_ttf-2.22.0.tar.gz
        tar -xzvf SDL2_ttf-2.22.0.tar.gz
        cd SDL2_ttf-2.22.0
        ./configure --prefix=/tmp/.sdl/SDL2_ttf-2.22.0
        make
        sudo make install
      env:
        PKG_CONFIG_PATH: /tmp/.sdl/SDL2-2.30.5/lib/pkgconfig:$PKG_CONFIG_PATH

    - if: ${{ inputs.CACHE_SDL_TTF != 'false' }} && steps.cache-sdl-ttf.outputs.cache-hit != 'true'
      name: Store SDL2 Cache
      uses: actions/cache/save@v4.0.2
      with:
        path: /tmp/.sdl/SDL2_ttf-2.22.0
        key: sdl2-${{ runner.os }}-sdl-ttf
