name: 'Install SDL Packages'
description: 'Install SDL packages'
author: 'Scott Doxey @neogeek'
branding:
  color: blue
  icon: upload-cloud

inputs:
  SDL2_VERSION:
    description: 'SDL2 version'
    required: false
    default: '2.32.4'
  CACHE_SDL:
    description: 'If the action should cache the SDL files.'
    required: false
    default: 'true'
  SDL2_IMAGE_VERSION:
    description: 'SDL2_image version'
    required: false
    default: '2.8.8'
  CACHE_SDL_IMAGE:
    description: 'If the action should cache the SDL_image files.'
    required: false
    default: 'true'
  SDL2_TTF_VERSION:
    description: 'SDL2_ttf version'
    required: false
    default: '2.24.0'
  CACHE_SDL_TTF:
    description: 'If the action should cache the SDL_ttf files.'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Restore SDL2 Cache
      uses: actions/cache/restore@v4.2.0
      id: cache-sdl
      with:
        path: /tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}
        key: sdl2-${{ inputs.SDL2_VERSION }}-${{ runner.os }}

    - if: steps.cache-sdl.outputs.cache-hit != 'true'
      name: Install SDL2
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL/releases/download/release-${{ inputs.SDL2_VERSION }}/SDL2-${{ inputs.SDL2_VERSION }}.tar.gz
        tar -xzvf SDL2-${{ inputs.SDL2_VERSION }}.tar.gz
        cd SDL2-${{ inputs.SDL2_VERSION }}
        ./configure --prefix=/tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}
        make
        sudo make install

    - if: ${{ inputs.CACHE_SDL != 'false' }} && steps.cache-sdl.outputs.cache-hit != 'true'
      name: Store SDL2 Cache
      uses: actions/cache/save@v4.2.0
      with:
        path: /tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}
        key: sdl2-${{ inputs.SDL2_VERSION }}-${{ runner.os }}

    - name: Restore SDL2_image Cache
      uses: actions/cache/restore@v4.2.0
      id: cache-sdl-image
      with:
        path: /tmp/.sdl/SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}
        key: sdl2-image-${{ inputs.SDL2_IMAGE_VERSION }}-${{ runner.os }}

    - if: steps.cache-sdl-image.outputs.cache-hit != 'true'
      name: Install SDL_image
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL_image/releases/download/release-${{ inputs.SDL2_IMAGE_VERSION }}/SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}.tar.gz
        tar -xzvf SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}.tar.gz
        cd SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}
        ./configure --prefix=/tmp/.sdl/SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}
        make
        sudo make install
      env:
        PKG_CONFIG_PATH: /tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}/lib/pkgconfig:$PKG_CONFIG_PATH

    - if: ${{ inputs.CACHE_SDL_IMAGE != 'false' }} && steps.cache-sdl-image.outputs.cache-hit != 'true'
      name: Store SDL2_image Cache
      uses: actions/cache/save@v4.2.0
      with:
        path: /tmp/.sdl/SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}
        key: sdl2-image-${{ inputs.SDL2_IMAGE_VERSION }}-${{ runner.os }}

    - name: Restore SDL2_ttf Cache
      uses: actions/cache/restore@v4.2.0
      id: cache-sdl-ttf
      with:
        path: /tmp/.sdl/SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}
        key: sdl2-ttf-${{ inputs.SDL2_TTF_VERSION }}-${{ runner.os }}

    - if: steps.cache-sdl-ttf.outputs.cache-hit != 'true'
      name: Install SDL_ttf
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL_ttf/releases/download/release-${{ inputs.SDL2_TTF_VERSION }}/SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}.tar.gz
        tar -xzvf SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}.tar.gz
        cd SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}
        ./configure --prefix=/tmp/.sdl/SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}
        make
        sudo make install
      env:
        PKG_CONFIG_PATH: /tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}/lib/pkgconfig:$PKG_CONFIG_PATH

    - if: ${{ inputs.CACHE_SDL_TTF != 'false' }} && steps.cache-sdl-ttf.outputs.cache-hit != 'true'
      name: Store SDL2 Cache
      uses: actions/cache/save@v4.2.0
      with:
        path: /tmp/.sdl/SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}
        key: sdl2-ttf-${{ inputs.SDL2_TTF_VERSION }}-${{ runner.os }}
