name: "Install SDL Packages"
description: "Install SDL packages"
author: "Scott Doxey @neogeek"
branding:
  color: blue
  icon: upload-cloud

inputs:
  SDL2_VERSION:
    description: "SDL version"
    required: false
    default: "2.32.6"
  CACHE_SDL:
    description: "If the action should cache the SDL files."
    required: false
    default: "true"
  SDL2_IMAGE_VERSION:
    description: "SDL_image version"
    required: false
    default: "2.8.8"
  CACHE_SDL_IMAGE:
    description: "If the action should cache the SDL_image files."
    required: false
    default: "true"
  SDL2_TTF_VERSION:
    description: "SDL_ttf version"
    required: false
    default: "2.24.0"
  CACHE_SDL_TTF:
    description: "If the action should cache the SDL_ttf files."
    required: false
    default: "true"
  SDL2_MIXER_VERSION:
    description: "SDL_mixer version"
    required: false
    default: "2.8.1"
  CACHE_SDL_MIXER:
    description: "If the action should cache the SDL_mixer files."
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - if: ${{ inputs.SDL2_VERSION != '' }}
      name: Restore SDL Cache
      uses: actions/cache/restore@v4.2.0
      id: cache-sdl
      with:
        path: /tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}
        key: sdl-${{ inputs.SDL2_VERSION }}-${{ runner.os }}

    - if: ${{ inputs.SDL2_VERSION != '' && steps.cache-sdl.outputs.cache-hit != 'true' }}
      name: Install SDL
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL/releases/download/release-${{ inputs.SDL2_VERSION }}/SDL2-${{ inputs.SDL2_VERSION }}.tar.gz
        tar -xzvf SDL2-${{ inputs.SDL2_VERSION }}.tar.gz
        cd SDL2-${{ inputs.SDL2_VERSION }}
        ./configure --prefix=/tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}
        make -j$(nproc)
        make install

    - if: ${{ inputs.SDL2_VERSION != '' && inputs.CACHE_SDL != 'false' && steps.cache-sdl.outputs.cache-hit != 'true' }}
      name: Store SDL Cache
      uses: actions/cache/save@v4.2.0
      with:
        path: /tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}
        key: sdl-${{ inputs.SDL2_VERSION }}-${{ runner.os }}

    - if: ${{ inputs.SDL2_IMAGE_VERSION != '' }}
      name: Restore SDL_image Cache
      uses: actions/cache/restore@v4.2.0
      id: cache-sdl-image
      with:
        path: /tmp/.sdl/SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}
        key: sdl-image-${{ inputs.SDL2_IMAGE_VERSION }}-${{ runner.os }}

    - if: ${{ inputs.SDL2_IMAGE_VERSION != '' && steps.cache-sdl-image.outputs.cache-hit != 'true' }}
      name: Install SDL_image
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL_image/releases/download/release-${{ inputs.SDL2_IMAGE_VERSION }}/SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}.tar.gz
        tar -xzvf SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}.tar.gz
        cd SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}
        ./configure --prefix=/tmp/.sdl/SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}
        make -j$(nproc)
        make install
      env:
        PKG_CONFIG_PATH: /tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}/lib/pkgconfig:$PKG_CONFIG_PATH

    - if: ${{ inputs.SDL2_IMAGE_VERSION != '' && inputs.CACHE_SDL_IMAGE != 'false' && steps.cache-sdl-image.outputs.cache-hit != 'true' }}
      name: Store SDL_image Cache
      uses: actions/cache/save@v4.2.0
      with:
        path: /tmp/.sdl/SDL2_image-${{ inputs.SDL2_IMAGE_VERSION }}
        key: sdl-image-${{ inputs.SDL2_IMAGE_VERSION }}-${{ runner.os }}

    - if: ${{ inputs.SDL2_TTF_VERSION != '' }}
      name: Restore SDL_ttf Cache
      uses: actions/cache/restore@v4.2.0
      id: cache-sdl-ttf
      with:
        path: /tmp/.sdl/SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}
        key: sdl-ttf-${{ inputs.SDL2_TTF_VERSION }}-${{ runner.os }}

    - if: ${{ inputs.SDL2_TTF_VERSION != '' && steps.cache-sdl-ttf.outputs.cache-hit != 'true' }}
      name: Install SDL_ttf
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL_ttf/releases/download/release-${{ inputs.SDL2_TTF_VERSION }}/SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}.tar.gz
        tar -xzvf SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}.tar.gz
        cd SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}
        ./configure --prefix=/tmp/.sdl/SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}
        make -j$(nproc)
        make install
      env:
        PKG_CONFIG_PATH: /tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}/lib/pkgconfig:$PKG_CONFIG_PATH

    - if: ${{ inputs.SDL2_TTF_VERSION != '' && inputs.CACHE_SDL_TTF != 'false' && steps.cache-sdl-ttf.outputs.cache-hit != 'true' }}
      name: Store SDL_ttf Cache
      uses: actions/cache/save@v4.2.0
      with:
        path: /tmp/.sdl/SDL2_ttf-${{ inputs.SDL2_TTF_VERSION }}
        key: sdl-ttf-${{ inputs.SDL2_TTF_VERSION }}-${{ runner.os }}

    - if: ${{ inputs.SDL2_MIXER_VERSION != '' }}
      name: Restore SDL_mixer Cache
      uses: actions/cache/restore@v4.2.0
      id: cache-sdl-mixer
      with:
        path: /tmp/.sdl/SDL2_mixer-${{ inputs.SDL2_MIXER_VERSION }}
        key: sdl-mixer-${{ inputs.SDL2_MIXER_VERSION }}-${{ runner.os }}

    - if: ${{ inputs.SDL2_MIXER_VERSION != '' && steps.cache-sdl-mixer.outputs.cache-hit != 'true' }}
      name: Install SDL_mixer
      shell: bash
      run: |
        mkdir -p /tmp/.sdl
        cd /tmp/.sdl
        curl -LO https://github.com/libsdl-org/SDL_mixer/releases/download/release-${{ inputs.SDL2_MIXER_VERSION }}/SDL2_mixer-${{ inputs.SDL2_MIXER_VERSION }}.tar.gz
        tar -xzvf SDL2_mixer-${{ inputs.SDL2_MIXER_VERSION }}.tar.gz
        cd SDL2_mixer-${{ inputs.SDL2_MIXER_VERSION }}
        ./configure --prefix=/tmp/.sdl/SDL2_mixer-${{ inputs.SDL2_MIXER_VERSION }}
        make -j$(nproc)
        make install
      env:
        PKG_CONFIG_PATH: /tmp/.sdl/SDL2-${{ inputs.SDL2_VERSION }}/lib/pkgconfig:$PKG_CONFIG_PATH

    - if: ${{ inputs.SDL2_MIXER_VERSION != '' && inputs.CACHE_SDL_MIXER != 'false' && steps.cache-sdl-mixer.outputs.cache-hit != 'true' }}
      name: Store SDL_mixer Cache
      uses: actions/cache/save@v4.2.0
      with:
        path: /tmp/.sdl/SDL2_mixer-${{ inputs.SDL2_MIXER_VERSION }}
        key: sdl-mixer-${{ inputs.SDL2_MIXER_VERSION }}-${{ runner.os }}
