name: Tests

on:
  push:
    branches:
      - main
    paths:
      - "*.yml"
      - ".github/workflows/*.yml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - "*.yml"
      - ".github/workflows/*.yml"
  workflow_dispatch:
    inputs:
      SDL2_VERSION:
        description: "SDL version"
        required: false
        default: "2.32.6"
      CACHE_SDL:
        description: "If the action should cache the SDL files."
        required: false
        default: "true"
      SDL2_IMAGE_VERSION:
        description: "SDL_image version"
        required: false
        default: "2.8.8"
      CACHE_SDL_IMAGE:
        description: "If the action should cache the SDL_image files."
        required: false
        default: "true"
      SDL2_TTF_VERSION:
        description: "SDL_ttf version"
        required: false
        default: "2.24.0"
      CACHE_SDL_TTF:
        description: "If the action should cache the SDL_ttf files."
        required: false
        default: "true"
      SDL2_MIXER_VERSION:
        description: "SDL_mixer version"
        required: false
        default: "2.8.1"
      CACHE_SDL_MIXER:
        description: "If the action should cache the SDL_mixer files."
        required: false
        default: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install SDL dependencies
        uses: ./
        with:
          CACHE_SDL: ${{ inputs.CACHE_SDL || 'true' }}
          SDL2_VERSION: ${{ inputs.SDL2_VERSION || '2.32.6' }}
          SDL2_IMAGE_VERSION: ${{ inputs.SDL2_IMAGE_VERSION || '2.8.8' }}
          CACHE_SDL_IMAGE: ${{ inputs.CACHE_SDL_IMAGE || 'true' }}
          SDL2_TTF_VERSION: ${{ inputs.SDL2_TTF_VERSION || '2.24.0' }}
          CACHE_SDL_TTF: ${{ inputs.CACHE_SDL_TTF || 'true' }}
          SDL2_MIXER_VERSION: ${{ inputs.SDL2_MIXER_VERSION || '2.8.1' }}
          CACHE_SDL_MIXER: ${{ inputs.CACHE_SDL_MIXER || 'true' }}
